const fs = require('fs');
const path = require('path');

const lines = [];
lines.push('<!DOCTYPE html>');
lines.push('<html lang="en">');
lines.push('<head>');
lines.push('<meta charset="UTF-8"/>');
lines.push('<meta name="viewport" content="width=device-width, initial-scale=1.0"/>');
lines.push('<title>Access NQR \u2014 Smart QR Sharing</title>');
lines.push('<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>');
lines.push('<link rel="stylesheet" href="styles.css?v=premium_final"/>');
lines.push('<script src="config.js"></script>');
lines.push('<script src="backend.js"></script>');
lines.push('<style>');
lines.push('*, html, body { box-sizing: border-box; }');
lines.push('::-webkit-scrollbar { display: none; }');
lines.push('* { -ms-overflow-style: none; scrollbar-width: none; }');
lines.push('html { overflow: hidden; height: 100%; }');
lines.push('body { overflow-x: hidden; overflow-y: auto; margin: 0; padding: 0; height: 100%; }');
lines.push(':root {');
lines.push('  --c-navy-deep: #05070a;');
lines.push('  --c-text: #ffffff;');
lines.push('  --c-text-2: #a0a0a0;');
lines.push('  --c-text-3: #707070;');
lines.push('  --c-red: #d90429;');
lines.push("  --font-body: 'Inter', sans-serif;");
lines.push("  --font-display: 'Outfit', sans-serif;");
lines.push('  --sp-sm: 8px; --sp-md: 16px; --sp-lg: 24px; --sp-xl: 32px; --sp-2xl: 48px; --sp-4xl: 80px;');
lines.push('  --r-md: 12px; --r-lg: 20px;');
lines.push('}');
lines.push('.auth-page { display: flex; min-height: 100vh; background: var(--c-navy-deep); color: var(--c-text); font-family: var(--font-body); margin: 0; overflow-x: hidden; }');
lines.push('.auth-sidebar { flex: 1.2; background: radial-gradient(circle at top right, #1a1c2c, #05070a); position: relative; overflow: hidden; display: flex; flex-direction: column; justify-content: center; padding: var(--sp-4xl); }');
lines.push('.auth-sidebar::before { content: ""; position: absolute; inset: 0; background-image: linear-gradient(rgba(255,255,255,0.02) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.02) 1px, transparent 1px); background-size: 40px 40px; }');
lines.push('.auth-main { flex: 1; display: flex; flex-direction: column; justify-content: center; align-items: center; padding: var(--sp-2xl); position: relative; z-index: 10; background: var(--c-navy-deep); overflow-y: auto; }');
lines.push('.auth-box { width: 100%; max-width: 440px; }');
lines.push('.auth-glow { position: absolute; width: 600px; height: 600px; background: radial-gradient(circle, rgba(217,4,41,0.15) 0%, transparent 70%); filter: blur(80px); top: -100px; right: -100px; pointer-events: none; }');
lines.push('.swipe-overlay { position: fixed; top: 0; left: 0; width: 100%; height: 100%; transform: translateX(-120%); background: linear-gradient(90deg, transparent 0%, rgba(217, 4, 41, 0.8) 40%, rgba(239, 35, 60, 1) 50%, rgba(217, 4, 41, 0.8) 60%, transparent 100%); z-index: 9999; pointer-events: none; backdrop-filter: blur(8px); }');
// swipe-overlay.is-active is now included above
lines.push('.swipe-overlay.is-active { animation: swipe 0.8s cubic-bezier(0.65, 0, 0.35, 1) forwards; }');
lines.push('@keyframes swipe { 0% { transform: translateX(-120%) skewX(-15deg); } 50% { transform: translateX(0%) skewX(-5deg); } 100% { transform: translateX(120%) skewX(-15deg); } }');
lines.push('.form-content { transition: opacity 0.4s ease, transform 0.4s ease; }');
lines.push('.form-content.is-fading { opacity: 0; transform: translateY(10px); }');
lines.push('.nav__logo { display: flex; align-items: center; gap: var(--sp-sm); margin-bottom: 32px; text-decoration: none; font-family: var(--font-display); color: white; }');
lines.push('.nav__logo-mark { width: 42px; height: 42px; background: var(--c-red); border-radius: 50% !important; display: flex; align-items: center; justify-content: center; overflow: hidden; box-shadow: 0 0 20px rgba(217, 4, 41, 0.3); }');
lines.push('.nav__logo-mark img { width: 100%; height: 100%; object-fit: cover; }');
lines.push('.auth-headline { font-family: var(--font-display); font-size: 3rem; font-weight: 800; margin-bottom: 8px; letter-spacing: -1px; }');
lines.push('.auth-sub { color: var(--c-text-2); margin-bottom: 32px; font-size: 1rem; }');
lines.push('.form-group { margin-bottom: 24px; position: relative; }');
lines.push('.form-label { display: block; text-transform: uppercase; font-size: 0.75rem; letter-spacing: 1px; color: var(--c-text-3); font-weight: 700; margin-bottom: 8px; }');
lines.push('.form-input { width: 100%; background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1); padding: 16px; border-radius: var(--r-md); color: white; font-size: 1rem; box-sizing: border-box; transition: border-color 0.2s; }');
lines.push('.form-input:focus { border-color: var(--c-red); outline: none; box-shadow: 0 0 0 3px rgba(217,4,41,0.1); }');
lines.push('.turnstile-wrap { margin: 32px 0; display: flex; justify-content: center; min-height: 65px; border: 1px solid rgba(255,255,255,0.1); border-radius: var(--r-md); background: rgba(0,0,0,0.25); padding: 10px; }');
lines.push('.btn-auth { width: 100%; padding: 18px; border-radius: 50px; border: none; font-family: var(--font-display); font-weight: 700; font-size: 1.1rem; cursor: pointer; background: linear-gradient(135deg, #d90429, #ef233c); color: white; box-shadow: 0 8px 32px rgba(217, 4, 41, 0.3); transition: transform 0.2s, box-shadow 0.2s; }');
lines.push('.btn-auth:hover { transform: translateY(-2px); box-shadow: 0 12px 40px rgba(217, 4, 41, 0.5); }');
lines.push('.switch-box { background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.05); border-radius: var(--r-lg); padding: 32px; text-align: center; margin-top: 48px; }');
lines.push('.switch-link { color: white; font-weight: 700; cursor: pointer; }');
lines.push('[data-mode="signup"] .login-only, [data-mode="login"] .signup-only { display: none; }');
lines.push('@media (max-width: 900px) { .auth-sidebar { display: none; } }');
lines.push('</style>');
lines.push('</head>');
lines.push('<body class="auth-page" data-mode="login">');
lines.push('<div class="swipe-overlay" id="swipeOverlay"></div>');
lines.push('<div class="auth-main">');
lines.push('  <div class="auth-glow"></div>');
lines.push('  <div class="auth-box">');
lines.push('    <a href="index.html" class="nav__logo">');
lines.push('      <div class="nav__logo-mark"><img src="assets/logo.png" alt="NQR Logo"></div>');
lines.push('      <div><div class="nav__logo-text">NQR</div><div class="nav__logo-powered">Powered by Neverno</div></div>');
lines.push('    </a>');
lines.push('    <div class="form-content" id="formContent">');
lines.push('      <div>');
lines.push('        <h1 class="auth-headline login-only">Welcome back</h1>');
lines.push('        <h1 class="auth-headline signup-only">Join NQR</h1>');
lines.push('        <p class="auth-sub login-only">Sign in to start generating and sharing QRs.</p>');
lines.push('        <p class="auth-sub signup-only">Create an account to save and track your QRs.</p>');
lines.push('      </div>');
lines.push('      <div id="authError" style="color:#ef233c;background:rgba(239,35,60,0.1);padding:12px;border-radius:8px;margin-bottom:24px;display:none;text-align:center;border:1px solid rgba(239,35,60,0.2);"></div>');
lines.push('      <form onsubmit="handleAuthSubmit(event, this)">');
lines.push('        <div class="signup-only"><div class="form-group"><label class="form-label">Full Name</label><input type="text" class="form-input" placeholder="Jane Doe"/></div></div>');
lines.push('        <div class="form-group"><label class="form-label">Email Address</label><input type="email" class="form-input" placeholder="jane@neverno.in" required/></div>');
lines.push('        <div class="form-group"><label class="form-label">Password</label><input type="password" id="authPassword" class="form-input" placeholder="\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022" required/></div>');
lines.push('        <div class="turnstile-wrap"><div class="cf-turnstile" data-sitekey="1x00000000000000000000AA" data-theme="dark"></div></div>');
lines.push('        <button type="submit" class="btn-auth"><span class="login-only">Sign In</span><span class="signup-only">Create Account</span></button>');
lines.push('      </form>');
lines.push('      <div class="switch-box">');
lines.push('        <div class="switch-text login-only">Don\'t have an account? <span class="switch-link" onclick="handleSwitch(\'signup\')">Join NQR</span></div>');
lines.push('        <div class="switch-text signup-only">Already have an account? <span class="switch-link" onclick="handleSwitch(\'login\')">Sign In</span></div>');
lines.push('      </div>');
lines.push('    </div>');
lines.push('  </div>');
lines.push('</div>');
lines.push('<div class="auth-sidebar">');
lines.push('  <div class="auth-glow" style="top:auto;bottom:-100px;left:-100px;background:radial-gradient(circle,rgba(42,62,143,0.2) 0%,transparent 70%);"></div>');
lines.push('  <div>');
lines.push('    <h2 class="auth-headline" style="font-size:3.5rem;line-height:1.1">Sharing<br/>Simplified.</h2>');
lines.push('    <p class="auth-sub" style="font-size:1.2rem;max-width:400px;">Experience the next generation of link sharing with NQR. Branded, secure, and instant.</p>');
lines.push('  </div>');
lines.push('</div>');
lines.push('<script>');
lines.push('var overlay = document.getElementById("swipeOverlay");');
lines.push('var formContent = document.getElementById("formContent");');
lines.push('function handleSwitch(mode) {');
lines.push('  overlay.classList.add("is-active");');
lines.push('  formContent.classList.add("is-fading");');
lines.push('  setTimeout(function() { document.body.setAttribute("data-mode", mode); }, 400);');
lines.push('  setTimeout(function() { formContent.classList.remove("is-fading"); }, 500);');
lines.push('  setTimeout(function() { overlay.classList.remove("is-active"); }, 800);');
lines.push('}');
lines.push('function handleAuthSubmit(e, form) {');
lines.push('  e.preventDefault();');
lines.push('  var errorEl = document.getElementById("authError");');
lines.push('  errorEl.style.display = "none";');
lines.push('  var tr = form.querySelector("[name=\\"cf-turnstile-response\\"]");');
lines.push('  if (!tr || !tr.value) { errorEl.textContent = "Please complete the security check."; errorEl.style.display = "block"; return; }');
lines.push('  var email = form.querySelector("input[type=email]").value;');
lines.push('  if (!email.toLowerCase().endsWith("@neverno.in")) { errorEl.textContent = "Use your @neverno.in email address."; errorEl.style.display = "block"; return; }');
lines.push('  window.location.href = "app-generator.html";');
lines.push('}');
lines.push('<\/script>');
lines.push('</body>');
lines.push('</html>');

const output = lines.join('\n');
fs.writeFileSync(path.join(__dirname, 'user-login.html'), output, { encoding: 'utf8', flag: 'w' });
console.log('Done! Lines written:', lines.length);
console.log('File size:', fs.statSync(path.join(__dirname, 'user-login.html')).size, 'bytes');
// Verify first line
const verify = fs.readFileSync(path.join(__dirname, 'user-login.html'), 'utf8').split('\n').slice(0, 5).join(' | ');
console.log('First 5 lines:', verify);
