version = 0.1
[default.deploy.parameters]
stack_name = "nqr-production"
region = "eu-north-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
s3_prefix = "nqr-production"
fail_on_empty_changeset = false
