# Generated by Django 6.0.2 on 2026-04-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_engine', '0002_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='url',
            field=models.TextField(),
        ),
    ]
