# Generated by Django 6.0.2 on 2026-04-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_engine', '0003_alter_qrcode_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
