# Generated by Django 6.0.2 on 2026-04-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='pending_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
